/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProjecaoBalancoRouteImport } from './routes/_app.projecao-balanco'
import { Route as AppFluxoDeCaixaRouteImport } from './routes/_app.fluxo-de-caixa'
import { Route as AppDreRouteImport } from './routes/_app.dre'
import { Route as AppCicloFinanceiroRouteImport } from './routes/_app.ciclo-financeiro'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as ApiPublicHooksOmieSyncNowRouteImport } from './routes/api/public/hooks/omie-sync-now'
import { Route as ApiPublicHooksOmieSyncRouteImport } from './routes/api/public/hooks/omie-sync'
import { Route as ApiPublicHooksImportYallaModeloRouteImport } from './routes/api/public/hooks/import-yalla-modelo'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjecaoBalancoRoute = AppProjecaoBalancoRouteImport.update({
  id: '/projecao-balanco',
  path: '/projecao-balanco',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoDeCaixaRoute = AppFluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppDreRoute = AppDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AppRoute,
} as any)
const AppCicloFinanceiroRoute = AppCicloFinanceiroRouteImport.update({
  id: '/ciclo-financeiro',
  path: '/ciclo-financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksOmieSyncNowRoute =
  ApiPublicHooksOmieSyncNowRouteImport.update({
    id: '/api/public/hooks/omie-sync-now',
    path: '/api/public/hooks/omie-sync-now',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOmieSyncRoute = ApiPublicHooksOmieSyncRouteImport.update({
  id: '/api/public/hooks/omie-sync',
  path: '/api/public/hooks/omie-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksImportYallaModeloRoute =
  ApiPublicHooksImportYallaModeloRouteImport.update({
    id: '/api/public/hooks/import-yalla-modelo',
    path: '/api/public/hooks/import-yalla-modelo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/ciclo-financeiro': typeof AppCicloFinanceiroRoute
  '/dre': typeof AppDreRoute
  '/fluxo-de-caixa': typeof AppFluxoDeCaixaRoute
  '/projecao-balanco': typeof AppProjecaoBalancoRoute
  '/api/public/hooks/import-yalla-modelo': typeof ApiPublicHooksImportYallaModeloRoute
  '/api/public/hooks/omie-sync': typeof ApiPublicHooksOmieSyncRoute
  '/api/public/hooks/omie-sync-now': typeof ApiPublicHooksOmieSyncNowRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/ciclo-financeiro': typeof AppCicloFinanceiroRoute
  '/dre': typeof AppDreRoute
  '/fluxo-de-caixa': typeof AppFluxoDeCaixaRoute
  '/projecao-balanco': typeof AppProjecaoBalancoRoute
  '/': typeof AppIndexRoute
  '/api/public/hooks/import-yalla-modelo': typeof ApiPublicHooksImportYallaModeloRoute
  '/api/public/hooks/omie-sync': typeof ApiPublicHooksOmieSyncRoute
  '/api/public/hooks/omie-sync-now': typeof ApiPublicHooksOmieSyncNowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/ciclo-financeiro': typeof AppCicloFinanceiroRoute
  '/_app/dre': typeof AppDreRoute
  '/_app/fluxo-de-caixa': typeof AppFluxoDeCaixaRoute
  '/_app/projecao-balanco': typeof AppProjecaoBalancoRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/hooks/import-yalla-modelo': typeof ApiPublicHooksImportYallaModeloRoute
  '/api/public/hooks/omie-sync': typeof ApiPublicHooksOmieSyncRoute
  '/api/public/hooks/omie-sync-now': typeof ApiPublicHooksOmieSyncNowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/ciclo-financeiro'
    | '/dre'
    | '/fluxo-de-caixa'
    | '/projecao-balanco'
    | '/api/public/hooks/import-yalla-modelo'
    | '/api/public/hooks/omie-sync'
    | '/api/public/hooks/omie-sync-now'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/ciclo-financeiro'
    | '/dre'
    | '/fluxo-de-caixa'
    | '/projecao-balanco'
    | '/'
    | '/api/public/hooks/import-yalla-modelo'
    | '/api/public/hooks/omie-sync'
    | '/api/public/hooks/omie-sync-now'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/ciclo-financeiro'
    | '/_app/dre'
    | '/_app/fluxo-de-caixa'
    | '/_app/projecao-balanco'
    | '/_app/'
    | '/api/public/hooks/import-yalla-modelo'
    | '/api/public/hooks/omie-sync'
    | '/api/public/hooks/omie-sync-now'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksImportYallaModeloRoute: typeof ApiPublicHooksImportYallaModeloRoute
  ApiPublicHooksOmieSyncRoute: typeof ApiPublicHooksOmieSyncRoute
  ApiPublicHooksOmieSyncNowRoute: typeof ApiPublicHooksOmieSyncNowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projecao-balanco': {
      id: '/_app/projecao-balanco'
      path: '/projecao-balanco'
      fullPath: '/projecao-balanco'
      preLoaderRoute: typeof AppProjecaoBalancoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxo-de-caixa': {
      id: '/_app/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof AppFluxoDeCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dre': {
      id: '/_app/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AppDreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ciclo-financeiro': {
      id: '/_app/ciclo-financeiro'
      path: '/ciclo-financeiro'
      fullPath: '/ciclo-financeiro'
      preLoaderRoute: typeof AppCicloFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/omie-sync-now': {
      id: '/api/public/hooks/omie-sync-now'
      path: '/api/public/hooks/omie-sync-now'
      fullPath: '/api/public/hooks/omie-sync-now'
      preLoaderRoute: typeof ApiPublicHooksOmieSyncNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/omie-sync': {
      id: '/api/public/hooks/omie-sync'
      path: '/api/public/hooks/omie-sync'
      fullPath: '/api/public/hooks/omie-sync'
      preLoaderRoute: typeof ApiPublicHooksOmieSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-yalla-modelo': {
      id: '/api/public/hooks/import-yalla-modelo'
      path: '/api/public/hooks/import-yalla-modelo'
      fullPath: '/api/public/hooks/import-yalla-modelo'
      preLoaderRoute: typeof ApiPublicHooksImportYallaModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCicloFinanceiroRoute: typeof AppCicloFinanceiroRoute
  AppDreRoute: typeof AppDreRoute
  AppFluxoDeCaixaRoute: typeof AppFluxoDeCaixaRoute
  AppProjecaoBalancoRoute: typeof AppProjecaoBalancoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCicloFinanceiroRoute: AppCicloFinanceiroRoute,
  AppDreRoute: AppDreRoute,
  AppFluxoDeCaixaRoute: AppFluxoDeCaixaRoute,
  AppProjecaoBalancoRoute: AppProjecaoBalancoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksImportYallaModeloRoute: ApiPublicHooksImportYallaModeloRoute,
  ApiPublicHooksOmieSyncRoute: ApiPublicHooksOmieSyncRoute,
  ApiPublicHooksOmieSyncNowRoute: ApiPublicHooksOmieSyncNowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
