/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFluxoDeCaixaRouteImport } from './routes/_app.fluxo-de-caixa'
import { Route as AppDreRouteImport } from './routes/_app.dre'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoDeCaixaRoute = AppFluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppDreRoute = AppDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dre': typeof AppDreRoute
  '/fluxo-de-caixa': typeof AppFluxoDeCaixaRoute
}
export interface FileRoutesByTo {
  '/dre': typeof AppDreRoute
  '/fluxo-de-caixa': typeof AppFluxoDeCaixaRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/dre': typeof AppDreRoute
  '/_app/fluxo-de-caixa': typeof AppFluxoDeCaixaRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dre' | '/fluxo-de-caixa'
  fileRoutesByTo: FileRoutesByTo
  to: '/dre' | '/fluxo-de-caixa' | '/'
  id: '__root__' | '/_app' | '/_app/dre' | '/_app/fluxo-de-caixa' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxo-de-caixa': {
      id: '/_app/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/fluxo-de-caixa'
      preLoaderRoute: typeof AppFluxoDeCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dre': {
      id: '/_app/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AppDreRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDreRoute: typeof AppDreRoute
  AppFluxoDeCaixaRoute: typeof AppFluxoDeCaixaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDreRoute: AppDreRoute,
  AppFluxoDeCaixaRoute: AppFluxoDeCaixaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
